### PR TITLE
Add Ability to Save

### PR DESCRIPTION
**Pull request by mexicantexan**
Add ability to save psd files.

### CODE REVIEW

**Comment by mexicantexan** [comment]
Using an iterative approach to see which update breaks the examples build in circleci.

**Comment by mexicantexan** [comment]
Checkpoint: Dependencies updated. Ready to add in saving PSD files.

**Comment by ajjahn** [comment]
Over the past few months, I've been intermittently working on write support. It is still incomplete, but I went ahead and opened #63 when I noticed you're making similar efforts. Interested in joining forces?

**Comment by mexicantexan** [comment]
all changes are going to be done through https://github.com/chinedufn/psd/pull/63

**Pull request closed without merging**
